const donatioData = [
  {
    id: 23110001,
    status: "berjalan",
    pengirim: "Warteg Citra",
    alamatPengirim: "Jl Citra, Kota Malang",
    penerima: "Yayasan Abdul Bari",
    alamatPenerima: "Jl. Sulaiman No.5, Kota Malang",
    jam: "20:00",
    tanggal: "11/11/2023",
    daftarMakanan: [
      {
        id: 1,
        foodName: "Nasi Goreng Bari",
        portion: 20,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
      {
        id: 2,
        foodName: "Nasi Goreng Pedas",
        portion: 10,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
      {
        id: 3,
        foodName: "Mie Goreng",
        portion: 20,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
    ],
  },
  {
    id: 23110002,
    status: "diterima",
    pengirim: "Rumah Makan Tangkilsari",
    alamatPengirim: "Jl Raya Tangkilsari, Kabupaten Malang",
    penerima: "Yayasan Qolbun Salim",
    alamatPenerima: "Jl. Sunan Kalijaga Dalam No.8, Dinoyo",
    jam: "20:00",
    tanggal: "11/11/2023",
    daftarMakanan: [
      {
        id: 1,
        foodName: "Ayam Pedas",
        portion: 20,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
      {
        id: 2,
        foodName: "Gurame Asam Manis",
        portion: 10,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
      {
        id: 3,
        foodName: "Kikil Goreng",
        portion: 20,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
    ],
  },
  {
    id: 23110002,
    status: "diterima",
    pengirim: "Rumah Makan Tangkilsari",
    alamatPengirim: "Jl Raya Tangkilsari, Kabupaten Malang",
    penerima: "Yayasan Qolbun Salim",
    alamatPenerima: "Jl. Sunan Kalijaga Dalam No.8, Dinoyo",
    jam: "20:00",
    tanggal: "11/11/2023",
    daftarMakanan: [
      {
        id: 1,
        foodName: "Ayam Pedas",
        portion: 20,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
      {
        id: 2,
        foodName: "Gurame Asam Manis",
        portion: 10,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
      {
        id: 3,
        foodName: "Kikil Goreng",
        portion: 20,
        storing: "Kulkas",
        reheat: "Wajan",
        lastingPeriod: 2,
      },
    ],
  },
];

export default donatioData;
