import {
  lembagaPermasyarakatan1Malang,
  pantiAsuhanSunanAmpel,
  yayasanAbdulBari,
  yayasanQolbunSalim,
  yayasanManarulHuda,
  rumahSosialBelasKasih,
  griyaKasihSiloam,
  lembagaPemasyarakatanPerempuanKelasIIAMalang,
  yayasanPantiKristenJatim,
  pantiAsuhanSalman,
  pondokPesantrenRiyaadlotudDaimah,
  pondokPesantrenDaruttauhidMalang,
  yayasanPendidikanTunasBangsa,
  pondokLansiaAlIshlah,
  yayasanLembagaPPTQMasjidAlIkhlas,
} from "../assets/images/org-photos/orgPhotoIndex.js";

const orgData = [
  {
    id: 1,
    name: "Yayasan Abdul Bari",
    alamat: "Jl. Sulaiman No.5, Kota Malang",
    kategori: "Panti Asuhan",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "086271982345",
    email: "abdulbari2023@gmail.com",
    img: yayasanAbdulBari,
  },
  {
    id: 2,
    name: "Yayasan Qolbun Salim",
    alamat: "Jl. Sunan Kalijaga Dalam No.8, Dinoyo",
    kategori: "Panti Asuhan",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "083429871639231",
    email: "qsyayasan@gmail.com",
    img: yayasanQolbunSalim,
  },
  {
    id: 3,
    name: "Rumah Sosial Belas Kasih",
    alamat: "Karang Ampel, Karangwidoro, Kec. Dau",
    kategori: "Panti Jompo",
    status: "Membutuhkan",
    halal: "Non Halal",
    noHp: "089478654120",
    email: "pedulibelaskasih@gmail.com",
    img: rumahSosialBelasKasih,
  },
  {
    id: 4,
    name: "Yayasan Manarul Huda",
    alamat: "Jl. Sumbersari III No.235",
    kategori: "Panti Asuhan",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "0812345678910",
    email: "manarulhuda@gmail.com",
    img: yayasanManarulHuda,
  },
  {
    id: 5,
    name: "Panti Asuhan Sunan Ampel",
    alamat: "Jl. Sumbersari Gg. II No.99",
    kategori: "Panti Asuhan",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "08765432191011",
    email: "sunanampel20@gmail.com",
    img: pantiAsuhanSunanAmpel,
  },
  {
    id: 6,
    name: "Lapas Kelas I Malang",
    alamat: "Jl. Asahan, Bunulrejo, Kec. Blimbing",
    kategori: "Lembaga Permasyarakatan",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "0813579246810",
    email: "lapas1mlg@gmail.com",
    img: lembagaPermasyarakatan1Malang,
  },
  {
    id: 7,
    name: "Griya Kasih Siloam",
    alamat: "Jl. Sigura - Gura No.17, Karangbesuki",
    kategori: "Panti Jompo",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "081122334455",
    email: "siloamkasih@gmail.com",
    img: griyaKasihSiloam,
  },
  {
    id: 8,
    name: "Yayasan Panti Kristen Jatim",
    alamat: "Jl. Kampar No.6, Rampal Celaket, Kec. Klojen",
    kategori: "Panti Asuhan",
    status: "Membutuhkan",
    halal: "Non Halal",
    noHp: "08975431000129",
    email: "pankrisjatim@gmail.com",
    img: yayasanPantiKristenJatim,
  },
  {
    id: 9,
    name: "Lembaga Pemasyarakatan Perempuan Kelas IIA Malang",
    alamat: "Jl. Kebonsari, Kebonsari, Kec. Sukun",
    kategori: "Lembaga Permasyarakatan",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "0842769178001",
    email: "lapas2a@gmail.com",
    img: lembagaPemasyarakatanPerempuanKelasIIAMalang,
  },
  {
    id: 10,
    name: "Panti Asuhan Salman",
    alamat: "Jl. Raya Candi VI No.193, Karangbesuki",
    kategori: "Panti Asuhan",
    status: "Tidak Membutuhkan",
    halal: "Halal",
    noHp: "087609125410",
    email: "pantisalman@gmail.com",
    img: pantiAsuhanSalman,
  },
  {
    id: 11,
    name: "Pondok Pesantren Riyaadlotud Daimah",
    alamat: "Jl. Mayjen Panjaitan Gg. 17 No.137",
    kategori: "Lain-Lain",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "089988776655",
    email: "ponpesrd@gmail.com",
    img: pondokPesantrenRiyaadlotudDaimah,
  },
  {
    id: 12,
    name: "Yayasan Pendidikan Tunas Bangsa",
    alamat: "Jl. Sunan Ampel 3, Dinoyo",
    kategori: "Lain-Lain",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "089543029120",
    email: "tunasbangsa@gmail.com",
    img: yayasanPendidikanTunasBangsa,
  },
  {
    id: 13,
    name: "Pondok Pesantren Daruttauhid Malang",
    alamat: "Jl. Sunan Ampel 3, Dinoyo",
    kategori: "Lain-Lain",
    status: "Tidak Membutuhkan",
    halal: "Halal",
    noHp: "089988776655",
    email: "ponpesdaruttauhid@gmail.com",
    img: pondokPesantrenDaruttauhidMalang,
  },
  {
    id: 14,
    name: "Pondok Lansia Al-Ishlah",
    alamat: "Jl. Laksda Adi Sucipto No.30, Pandanwangi",
    kategori: "Panti Jompo",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "080001119998",
    email: "pondoklansiaishlahd@gmail.com",
    img: pondokLansiaAlIshlah,
  },
  {
    id: 15,
    name: "Yayasan Lembaga PPTQ Masjid Al Ikhlas",
    alamat: "Jl. Langsep No.21-A, Karangbesuki",
    kategori: "Lain-Lain",
    status: "Membutuhkan",
    halal: "Halal",
    noHp: "085678123490",
    email: "yayasanpptqalikhlas@gmail.com",
    img: yayasanLembagaPPTQMasjidAlIkhlas,
  },
];

export default orgData;
